name: 'Manually build app stack'
on:
  workflow_dispatch:
    inputs:
      branch: 
        description: Branch name
        required: true
        default: 'main'
        type: string
      type: 
        description: Stack type
        required: true
        default: 'java'
        type: choice
        options:
          - java
          - dotnet
jobs:
  call-workflow-passing-data:
    uses: oracle-quickstart/appstack/.github/workflows/build.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      type: ${{ github.event.inputs.type }}
