name: 'Build App Stack for Java'
on:
  workflow_dispatch:
    inputs:
      branch: 
        description: Branch name
        required: true
        default: 'main'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: create-artifact
        run: |
          mv java/* .
          APPLICATION_GROUP=$(cat interface-application-group-block.yaml)
          SSL_GROUP=$(cat interface-ssl-group-block.yaml)
          APPLICATION=$(cat interface-application-block.yaml)
          SSL=$(cat interface-ssl-block.yaml)
          sed 's/# [APPLICATION_GROUP_BLOCK]/${APPLICATION_GROUP}/g' interface.yaml > interface.yaml
          sed 's/# [SSL_GROUP_BLOCK]/${SSL_GROUP}/g' interface.yaml > interface.yaml
          sed 's/# [APPLICATION_BLOCK]/${APPLICATION}/g' interface.yaml > interface.yaml
          sed 's/# [SSL_BLOCK]/${SSL}/g' interface.yaml > interface.yaml
          zip -r ./appstackforjava.zip . -x "*.git*" -x "*.DS_Store" -x "images/*" -x "listing/*" -x ".github/*" -x "*.md" -x "troubleshooting/*" -x "tutorials/*" -x "screenshots/*" -x "*.md"
          ls -lai
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: appstackforjava
          path: ./appstackforjava.zip
